# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=255),
            preserve_default=False,
        ),
    ]
